# ============================================================
# AI SERVICE — QUARKUS  (bootstrap local)
# ============================================================

quarkus.application.name=ai-quarkus
quarkus.http.port=8081

quarkus.log.category."com.demo".level=DEBUG

# --- Config Server ---
quarkus.spring-cloud-config.url=http://localhost:8888
quarkus.spring-cloud-config.optional=true

# GEMINI_API_KEY must be set as environment variable
quarkus.langchain4j.gemini.api-key=${GEMINI_API_KEY}

# --- Kafka (solo en prod) ---
%prod.kafka.bootstrap.servers=${KAFKA_BROKERS:localhost:9092}

%prod.quarkus.spring-cloud-config.url=http://config-server:8888
%prod.quarkus.spring-cloud-config.optional=false
