# ============================================================
# ORDER SERVICE — QUARKUS  (bootstrap local)
# ============================================================

quarkus.application.name=order-quarkus
quarkus.http.port=8080

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Order Service — Quarkus

quarkus.log.category."com.demo".level=DEBUG

# --- Config Server (fail-fast=false → no bloquea el arranque si no está disponible) ---
quarkus.spring-cloud-config.url=http://localhost:8888
quarkus.spring-cloud-config.fail-fast=false

# --- Base de datos (solo en prod — Dev Services la configura solo en dev) ---
%prod.quarkus.datasource.username=${DB_USER:postgres}
%prod.quarkus.datasource.password=${DB_PASSWORD:postgres}
%prod.quarkus.datasource.reactive.url=${DB_URL:postgresql://localhost:5434/ordersdb}

# --- Kafka (solo en prod) ---
%prod.kafka.bootstrap.servers=${KAFKA_BROKERS:localhost:9092}

%prod.quarkus.spring-cloud-config.url=http://config-server:8888
%prod.quarkus.spring-cloud-config.fail-fast=true
