quarkus.application.name=notification-quarkus
quarkus.http.port=8082

quarkus.log.category."com.demo".level=DEBUG

# --- Config Server ---
quarkus.spring-cloud-config.url=http://localhost:8888
quarkus.spring-cloud-config.fail-fast=false

# --- Kafka (solo en prod) ---
%prod.kafka.bootstrap.servers=${KAFKA_BROKERS:localhost:9092}

# --- Prod: Config Server de producción ---
%prod.quarkus.spring-cloud-config.url=http://config-server:8888
%prod.quarkus.spring-cloud-config.fail-fast=true
