FROM eclipse-temurin:21-jre-alpine
WORKDIR /work
COPY --chown=1001 target/quarkus-app/lib/ /work/lib/
COPY --chown=1001 target/quarkus-app/*.jar /work/
COPY --chown=1001 target/quarkus-app/app/ /work/app/
COPY --chown=1001 target/quarkus-app/quarkus/ /work/quarkus/
EXPOSE 8081
USER 1001
ENTRYPOINT ["java", "-jar", "/work/quarkus-run.jar"]
